### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rpetrasch** [imixs/imixs-jsf-example#10]
Sorry if my questions are a bit "basic", but I am not an app server expert.
You referred to Jboss Wildfly, so I used this app server. Build with maven was fine. no problems.
But the Wildfly part gives me a little headache:
a) According to the description, I need a database pool named 'jdbc/workflow-db': There are only datasources in wildfly that I can create with the manager console that must (!) start with  'java:/' or 'java:jboss/'. I followed these steps https://developer.jboss.org/thread/239020, but get stuck.
b) According to the description, imixs-workflow defines default roles. But how I can define these roles? in the wildfly console there is no add button in order to define these roles. What exactly is to be done here?
c) According to the description, I need a JAAS security configuration named 'imixsrealm'. How this is done? In the jboss wildfly docs I couldn't find any info about JAAS security configuration, except here (again) https://developer.jboss.org/thread/239020.

```
<security-domain name="imixsrealm" cache-type="default">  
    <authentication>  
        <login-module code="Database" flag="required">  
            <module-option name="imixsrealm" value="java:/sec"/>  
            <module-option name="principalsQuery" value="select pwd from credential where uname=?"/>  
            <module-option name="rolesQuery" value="select urole, 'Roles' from credential where uname=?"/>  
        </login-module>  
    </authentication>  
</security-domain>  
```

The error I get is as follows (it clearly refers to the persistence provider):

`Cannot upload deployment: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"imixs-jsf-example-4.0.3.war\".FIRST_MODULE_USE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"imixs-jsf-example-4.0.3.war\".FIRST_MODULE_USE: WFLYSRV0153: Failed to process phase FIRST_MODULE_USE of deployment \"imixs-jsf-example-4.0.3.war\" Caused by: javax.persistence.PersistenceException: WFLYJPA0057: PersistenceProvider 'org.eclipse.persistence.jpa.PersistenceProvider' not found"},"WFLYCTL0412: Required services that are not installed:" => ["jboss.deployment.unit.\"imixs-jsf-example-4.0.3.war\".FIRST_MODULE_USE"],"WFLYCTL0180: Services with missing/unavailable dependencies" => undefined}`

Thank you and best regards
Roland

**Comment by rsoika** [comment]
**a)** Yes you are right, the Database Connection in Widlfly should look like this :

```
<datasource jta="true" jndi-name="java:/jdbc/workflow-db" pool-name="workflow-db" enabled="true" use-ccm="true">
  .....
</datasource>
```

This is from the configuration/standalone.xml 
It is in most cases easier when you stop the server, and edit the standalone.xml file directly (but make a backup copy before ;-)

By the way you can use any kind of database. Mostly we use mysql or postgreSQL.

**b)** The example assumes that you have any kind of a database security domain already.
In your case it would be easier, if you set-up just a simple file based security realm. 
In configuration/standalone.xml this looks like:

```
       <security-domain name="imixsrealm">
                    <authentication>
			<login-module code="UsersRoles" flag="required">
			    <module-option name="usersProperties" value="my-app-users.properties"/>
			    <module-option name="rolesProperties" value="my-app-roles.properties"/>
			</login-module>
                        <login-module code="RoleMapping" flag="required">
                            <module-option name="rolesProperties" value="file:${jboss.server.config.dir}/imixsrealm.properties"/>
                            <module-option name="replaceRole" value="false"/>
                        </login-module>
                    </authentication>
                </security-domain>
```

The users and roles files are placed also into the configuration/ folder. 
See also here: 
https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.3/html/Security_Guide/chap-Login_Modules.html#UsersRolesLoginModule


I know this is a little bit complex when you start with Java EE servers. But the concept of Imixs-Wokflow is to avoid any proprietary security or database concept. For that reason, security is based on the JAAS standard. This means you can configure any kind of login technology supported by Wildfly. 
What the application expects is only a JAAS security realm named 'imixsrealm'. This can be configured in various ways. 

If you have problems with the security you can activate the logger category "org.jboss.security"  in the standalone.xml file:

```
 ....
    <console-handler name="CONSOLE">
                <level name="TRACE"/>
                <formatter>
                    <named-formatter name="COLOR-PATTERN"/>
                </formatter>
            </console-handler>
 <logger category="org.jboss.security">
.....
 <level name="TRACE"/>
 </logger>
```

This will force willdfly to tell you everything going on in the login process. 
But first the deployment itself must succeeded. 

We want to provide a docker container in the future to simplify setup. We have done this with your imixs-microservice. It should be easy to start with this, but this is only a microservice with not frontend ui:
https://github.com/imixs/imixs-microservice

Don't hesitate to ask again.

**Comment by rpetrasch** [comment]
Thank you very much. That worked.
