### ISSUE TITLE
Document table not being created

### ISSUE THREAD

**Issue by mazimmer** [imixs/imixs-jsf-example#24]
When deploying the newly built WAR into WildFly 13/14, MariaDB, the table DOCUMENT is not created, resulting in error: "javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: java.sql.SQLSyntaxErrorException: Table 'workflow_db.DOCUMENT' doesn't exist Error Code: 1146 Call: SELECT ID, CREATED, DATA, MODIFIED, TYPE, VERSION FROM DOCUMENT WHERE (TYPE = ?) ORDER BY CREATED DESC bind => [1 parameter bound] Query: ReadAllQuery(referenceClass=Document sql="SELECT ID, CREATED, DATA, MODIFIED, TYPE, VERSION FROM DOCUMENT WHERE (TYPE = ?) ORDER BY CREATED DESC")"

Tables that are being created are:
+-----------------------+
| Tables_in_workflow_db |
+-----------------------+
| CALENDARITEM          |
| DOUBLEITEM            |
| INTEGERITEM           |
| READACCESS            |
| SEQUENCE              |
| TEXTITEM              |
| WRITEACCESS           |
+-----------------------+

**Comment by mazimmer** [comment]
Actually, comparing to the docker postgreSQL instance, there's more tables missing. Compare table list:

                List of relations
 Schema |        Name         | Type  |  Owner   
--------+---------------------+-------+----------
 public | calendaritem        | table | postgres
 public | document            | table | postgres
 public | doubleitem          | table | postgres
 public | entity              | table | postgres
 public | entity_calendaritem | table | postgres
 public | entity_doubleitem   | table | postgres
 public | entity_integeritem  | table | postgres
 public | entity_readaccess   | table | postgres
 public | entity_textitem     | table | postgres
 public | entity_writeaccess  | table | postgres
 public | entityindex         | table | postgres
 public | integeritem         | table | postgres
 public | readaccess          | table | postgres
 public | sequence            | table | postgres
 public | textitem            | table | postgres
 public | writeaccess         | table | postgres

**Comment by rsoika** [comment]
Yes this is strange. 
in your persistence.xml there should be the following entry:
```

  <persistence-unit name="org.imixs.workflow.jpa" transaction-type="JTA">	
    ....
   <jar-file>lib/imixs-workflow-engine-${org.imixs.workflow.version}.jar</jar-file>
```

were ${org.imixs.workflow.version} points to somthing like 4.3.6 or higher. 
Can you verify this? The corresponding .jar file should be located in the /WEB-INF/lib/ folder

During the deployment the application server should print log messaging like _...Table 'document' created_ or _...Table 'document' already exists...._

Can you verify this? Are there any error messages in your log file during the deployment?

Especally the

     .... persistence-unit name="org.imixs.workflow.jpa" 

is important. Because this name has changed from older Imixs-Workflow versions (before 3.x)
Please verify the persistence.xml file. If you post it I will help with this issue.

**Comment by rsoika** [comment]
I just updated the example to imixs-workflow latest version 4.4.3 and lucene version 7.5
#25

**Comment by mazimmer** [comment]
I have not changed the sample in any way, it's 4.0.10 as downloaded from GitHub.

So the persistence.xml reads:

<persistence version="1.0" xmlns="http://java.sun.com/xml/ns/persistence">

	

	
	<persistence-unit name="org.imixs.workflow.jpa" transaction-type="JTA">	
		<provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>	
		<jta-data-source>jdbc/workflow-db</jta-data-source>
		<jar-file>lib/imixs-workflow-engine-4.3.1.jar</jar-file>
		<properties>
			
			<property name="eclipselink.target-database" value="Auto" />
			<property name="eclipselink.ddl-generation" value="create-tables" />
			<property name="eclipselink.deploy-on-startup" value="true" />
			<property name="eclipselink.logging.level" value="INFO" />	

			
		</properties>				
	</persistence-unit>

**Comment by rsoika** [comment]
ok but you say the table 'document' is not part of your database - right?
So when you deploy your application there should be some kind of message concerning the document table. Can you look for such a log message?
