### ISSUE TITLE
Multiple Persistence Unit

### ISSUE THREAD

**Issue by 4asifm** [imixs/imixs-jsf-example#27]
Is it possible to have multiple persistence unit in the persistence.xml file when deploying imixs in a war. 

I have an web application which includes imixs workflow (as dependencies). I want to keep the application and workflow database separate. so I created two different persistence unit in persistence.xml.

under this situation the web-application fails to start -> container log below.

SEVERE [main] org.apache.openejb.config.ReportValidationResults.logResults FAIL ... ModelRestServiceV40:@PersistenceContext unitName required, multiple units available: ref "entityManager", available units [iz_avalon_PU, org.imixs.workflow.jpa]

**Comment by rsoika** [comment]
I think this is somehow possible. Take a look here: 
https://stackoverflow.com/questions/5356152/two-persistence-unit-in-one-persistence-xml
https://developer.jboss.org/thread/183910

But on the other hand, maybe there is a way for you to rethink your application architecture. In most of such cases it makes sense to separate the different aspects of your application in way of a micro-service architecture. So in the end you will have two different services. We started a client project based on jax-rs (https://github.com/imixs/imixs-melman). It could be worth to think about this....
Let me know what your opinion is.

**Comment by rsoika** [comment]
Have you solved the issue ?
