### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by medach** [imixs/imixs-jsf-example#5]
Salut,je suis intéressé  par imixs ,je suis débutant dans le domain de workflow ,je suis en train de developper une application J2EE et je me suis bloqué dés le début ... merci de m'aidez

**Comment by rsoika** [comment]
hi,
can you explain your issue in english?

**Comment by medach** [comment]
Hi, I'm interested in imixs, I am newbie in the workflow domain, I am
trying to develop a J2EE application and I'm stuck me from the beginning
... thank you for helping me

2016-02-09 14:42 GMT+01:00 Ralph Soika <notifications@github.com>:

**Comment by rsoika** [comment]
Have you accomplished to checkout and build the JSF Example Application? 
Which application Server are you using (GlassFIsh or Wildfly) ?
Which database did you use?

**Comment by medach** [comment]
Hi Dear,
We are beginners, we didn't get started yet this project is so important to
us, it's our poject of end of studies we may use oracle or mysql database ,
glassfish server ...
I would be very grateful for any help you could be able to do for me.
Thank's a lot.
Best regards.

**Comment by medach** [comment]
For more information about the subjet of my project it will hundle a
workflow system in my JEE application , so i don't know how to integrate
imixs , even i couldn't build your project .
So can you help with that please !
Thank you a lot.


>

**Comment by rsoika** [comment]
If you are working with maven it should not so hard to bundle the imixs-workflow into your project.
Just take a look at the pom.xml of the JSF example. In the WEB-INF/ folder of the project you can find the deployment descriptors to be used.
Maybe you share you own code so I can see what you try to do?

**Comment by medach** [comment]
thank you my freind , can you help in with teamviewer !!

2016-02-09 18:29 GMT+01:00 Ralph Soika <notifications@github.com>:

**Comment by rsoika** [comment]
No I am sorry. If you have a concrete question about Imixs-Workflow I will try to help you. But I can not offer you fee consulting. So try to ask a concrete question.

**Comment by medach** [comment]
Good morning,
How much does it costs ( talking about the consultation !) , I do really
need to underestand that ( how to integrate workflow in a JEE app and how
to use it ) it's important so that i can do my project.
Thank you.
Best regards.

2016-02-09 19:06 GMT+01:00 Ralph Soika <notifications@github.com>:

**Comment by rsoika** [comment]
Hi, you can send us an E-Mail to info@imixs.com. Please provide some information what's the goal of your project. Is it commercial? Are you working for an enterprise?
