### ISSUE TITLE
Deployment Guide - outdated information about JDBC Name

### ISSUE THREAD

**Issue by ozzi-** [imixs/imixs-jsf-example#50]
Hi there
Just realized (after an update of the example app from v.4 to v.5), that in standalone.xml:
```
jndi-name="java:/jdbc/workflow-db" pool-name="workflow-db"
```
should be
```
jndi-name="java:/jdbc/workflow" pool-name="workflow"
```
Your readme here on github says so, but the following guide:
https://www.imixs.org/doc/deployment/wildfly.html

Still says it needs to be workflow-db ;)

Cheers

**Comment by rsoika** [comment]
Yes you are right. I will fix this. Thanks for this finding!
