### ISSUE TITLE
Fresh Deployment to Wildfire - java.util.Hashtable cannot be cast to class java.sql.Blob 

### ISSUE THREAD

**Issue by e2021d** [imixs/imixs-jsf-example#55]
During deployment to a Widilfire server, an exception is thrown  as follows:

20:42:59,418 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "imixs-jsf-example.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"imixs-jsf-example.war\".component.SetupService.START" => "java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: javax.ejb.EJBTransactionRolledbackException: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
    Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
    Caused by: java.lang.ClassCastException: class java.util.Hashtable cannot be cast to class java.sql.Blob (java.util.Hashtable is in module java.base of loader 'bootstrap'; java.sql.Blob is in module java.sql of loader 'platform')"}}

I tried looking for the cause of the issue and all I can find is the Document and EventLog class that has a reference to @Lob.
Any help with solving the issue would be appreciated.

The servers are fresh Debian 10  with  WildFly Full 22.0.1.Final (WildFly Core 14.0.1.Final) installation.  Not docker build's but deployment as per the https://www.imixs.org/doc/deployment/wildfly.html document.

The database servers are remote (not localhost)   Postgres 13 and Mysql 8.0.21, 
More version details are found in the environment.txt file
Attached for each database type:
- standalone.xml
- log file from the wildfire server.log

[Environment.txt](https://github.com/imixs/imixs-jsf-example/files/5979458/Environment.txt)
[standaloneMysql.xml.txt](https://github.com/imixs/imixs-jsf-example/files/5979461/standaloneMysql.xml.txt)
[standalonePostgres.xml.txt](https://github.com/imixs/imixs-jsf-example/files/5979462/standalonePostgres.xml.txt)
[wildflyMysql_log.txt](https://github.com/imixs/imixs-jsf-example/files/5979463/wildflyMysql_log.txt)
[wildflyPostgres_log.txt](https://github.com/imixs/imixs-jsf-example/files/5979464/wildflyPostgres_log.txt)

**Comment by rsoika** [comment]
Hi,
have you installed the [eclipselink](https://www.eclipse.org/eclipselink/) module on wildfly? See a description here: https://www.imixs.org/doc/deployment/wildfly.html

I guess there is a problem with the hibernate OR-Mapper. We always work with the eclipselink OR-Mapper. 

If you like, we can figure out if the default or mapper can be used too. But first please make a test with the eclipseLink to sort out the root of the problem.

**Comment by e2021d** [comment]
Yes, eclipse link 2.7.7 is installed.  What is test that needs to be performed?

wildfly-22.0.1.Final# ls -l ./modules/system/layers/base/org/eclipse/persistence/main
total 9104
-rw-r--r-- 1 ed ed 9298849 Feb 15 03:43 eclipselink.jar
-rw-r--r-- 1 ed ed   12466 Feb 11 17:49 jipijapa-eclipselink-22.0.1.Final.jar
-rw-r--r-- 1 ed ed    2080 Feb 14 00:29 module.xml

wildfly-22.0.1.Final# grep eclipse standalone/configuration/standalone.xml
        <property name="eclipselink.archive.factory" value="org.jipijapa.eclipselink.JBossArchiveFactoryImpl"/>

wildfly-22.0.1.Final# more ./modules/system/layers/base/org/eclipse/persistence/main/module.xml
<?xml version="1.0" encoding="UTF-8"?>


<module name="org.eclipse.persistence" xmlns="urn:jboss:module:1.5">
    <properties>
        <property name="jboss.api" value="public"/>
    </properties>

    <resources>
        <resource-root path="jipijapa-eclipselink-22.0.1.Final.jar"/>
        <resource-root path="eclipselink.jar">
            <filter>
                    <exclude path="javax/**" />
            </filter>
        </resource-root>
    </resources>

    <dependencies>
        <module name="javax.api"/>
        <module name="javax.annotation.api"/>
        <module name="javax.enterprise.api"/>
        <module name="javax.persistence.api"/>
        <module name="javax.transaction.api"/>
        <module name="javax.validation.api"/>
        <module name="javax.xml.bind.api"/>
        <module name="org.antlr"/>
        <module name="org.dom4j"/>
        <module name="org.jboss.as.jpa.spi"/>
        <module name="org.jboss.logging"/>
        <module name="org.jboss.vfs"/>
    </dependencies>
</module>

**Comment by rsoika** [comment]
very strange. I will start creating a new build on wildfly version 22.0.1 final. I have not yet tested it with this version.

**Comment by rsoika** [comment]
I upgraded the docker jsf example to wildfly 22.0.1.final. I was not able to reproduce the deployment error.

You can take a look at my standalone.xml file [here](https://github.com/imixs/imixs-jsf-example/blob/master/docker/configuration/wildfly/standalone.xml)

Also take care about the eclipselink module.xml file [here](https://github.com/imixs/imixs-jsf-example/blob/master/docker/configuration/wildfly/modules/system/layers/base/org/eclipse/persistence/main/module.xml) 

If you take a look at the [Dockerfile](https://github.com/imixs/imixs-jsf-example/blob/master/Dockerfile) you can see how we add the application specific configuration to wildfly

**Comment by e2021d** [comment]
Thanks for the configurations.  They were like the ones already deployed.  I was not able run the Dockerfile build successfully for Debian 10.  On Centos 7 it worked  but the same deployment  error as above.

I pulled from the git the sources for the apps and rebuilt them on the wildfly host (debian10).  This solved the deployment issue.
Normally builds are performed on a build server and the target is then remotely deployed.
I had to tweak a couple of files:  
imixs.properties - Added two required parameter lines index.fields.analyze= & index.fields.noanalyze=
pom.xml:   org.imixs.workflow.version  = 5.2.8-SNAPSHOT
After the full rebuild, the project deployed successfully.
Thanks for your help.

**Comment by rsoika** [comment]
Great that it works now for you!
You should not use the snapshot versions for your project. Version 5.2.8 is final and there is no need to take a snapshot which can always have an unpredictable result. 

I still do not understand what causes the root of the problem in your scenario. From the log files it looks like the workflow engine was successfully initialized for both databases (mysql and psql). And the missing properties should not cause that kind of SQL error. 

Let me know if you run again into a problem.
