### ISSUE TITLE
Deployment error with Payara

### ISSUE THREAD

**Issue by carlez** [imixs/imixs-jsf-example#9]
I'm trying to run the sample application from the website (http://www.imixs.org/doc/sampleapplication.html)
I built the application with “mvn clean install -Pglassfish4” and now I have the war file.
When I try to deploy this war file with Payara I get this error: 
“Error occurred during deployment: Exception while deploying the app [imixs-jsf-example-4.0.1] : Error processing EjbDescriptor. Please see server.log for more details.”
Log file as attachment.
[log.txt](https://github.com/imixs/imixs-jsf-example/files/617472/log.txt)

**Comment by rsoika** [comment]
yes you are right, there was an error in the glassfish deployment descriptor. I have fixed this in the meantime. So you can try the latest updated version 4.0.2. I have tested this version with payara and it looks good. Let me hear if it works for you too.

**Comment by carlez** [comment]
Thank you! Now it works perfectly. The only problem I found in the sample application is that I can't create new tickets because the save button is missing.
![cattura](https://cloud.githubusercontent.com/assets/138191/20688647/0576ac04-b5c2-11e6-9990-0c8ca1329457.jpg)

**Comment by rsoika** [comment]
Make sure that a model (ticket.bpmn) is uploaded. You can do this with curl command:

`curl --user admin:adminpassword --request POST -Tticket.bpmn http://localhost:8080/workflow/rest-service/model/bpmn`

To check if a models available you can use the REST API via browser:

http://localhost:8080/workflow/rest-service/model
